In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification
import tensorflow as tf

In [3]:
# 生成二元分類數據集
X, y = make_classification(n_samples=1000, n_features=20, n_classes=2, random_state=0)

# 分割數據為訓練集和測試集
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# 標準化數據
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [4]:
# 建立多層二元分類神經網路
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_dim=X_train.shape[1]),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')  # 輸出層，使用 sigmoid 激活函數進行二元分類
])

In [5]:
# 設定優化器
optimizer = tf.keras.optimizers.Adam()
model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])

(1) Epoch使用訓練集全部資料模型進行"一次性"的完整訓練。所以也被稱為"一代訓練"。  
(2) Batch是用訓練集中的一小部分樣本對模型權重進行一次反向傳播的參數更新，這一小部分的訓練樣本被稱為"一批次量"。  
(3) Iteration 是使用一個Batch資料模型進行一次參數更新的過程，被稱為"一次訓練"。

- [batch size 相關文章](https://hyades910739.medium.com/%E8%AB%96%E6%96%87%E7%AD%86%E8%A8%98-batch-size-%E8%B6%8A%E5%B0%8F%E8%B6%8A%E5%A5%BD-%E9%80%99%E7%AF%87%E8%AB%96%E6%96%87%E9%80%99%E6%A8%A3%E8%AA%AA-5029de4afbeb)

In [6]:
# 訓練模型
model.fit(X_train, y_train, epochs=20, batch_size=32, validation_split=0.2) 

Epoch 1/20
18/18 [==============================] - 0s 5ms/step - loss: 0.6612 - accuracy: 0.5839 - val_loss: 0.5685 - val_accuracy: 0.7286
Epoch 2/20
18/18 [==============================] - 0s 2ms/step - loss: 0.4605 - accuracy: 0.8089 - val_loss: 0.2729 - val_accuracy: 0.9429
Epoch 3/20
18/18 [==============================] - 0s 2ms/step - loss: 0.2089 - accuracy: 0.9286 - val_loss: 0.1323 - val_accuracy: 0.9357
Epoch 4/20
18/18 [==============================] - 0s 2ms/step - loss: 0.1450 - accuracy: 0.9518 - val_loss: 0.1278 - val_accuracy: 0.9500
Epoch 5/20
18/18 [==============================] - 0s 2ms/step - loss: 0.1023 - accuracy: 0.9625 - val_loss: 0.1216 - val_accuracy: 0.9571
Epoch 6/20
18/18 [==============================] - 0s 2ms/step - loss: 0.0850 - accuracy: 0.9714 - val_loss: 0.1473 - val_accuracy: 0.9500
Epoch 7/20
18/18 [==============================] - 0s 2ms/step - loss: 0.0579 - accuracy: 0.9857 - val_loss: 0.1206 - val_accuracy: 0.9571
Epoch 8/20
18/18 [==

In [7]:
# 進行預測
predictions = model.predict(X_test)
print(predictions)

10/10 [==============================] - 0s 521us/step
[[3.63017927e-04]
 [9.89644759e-05]
 [9.99963045e-01]
 [8.97209929e-07]
 [9.98890221e-01]
 [1.00000000e+00]
 [9.99999762e-01]
 [2.24447078e-07]
 [9.99816716e-01]
 [2.84186867e-12]
 [9.99928534e-01]
 [1.54055317e-03]
 [9.99082685e-01]
 [9.99410212e-01]
 [2.67709249e-12]
 [2.52345217e-06]
 [9.99890506e-01]
 [9.89678860e-01]
 [9.99884188e-01]
 [1.73888196e-10]
 [2.22297494e-05]
 [9.99971986e-01]
 [9.99999821e-01]
 [6.19181928e-11]
 [9.99998987e-01]
 [9.96796787e-01]
 [9.93786931e-01]
 [9.99993563e-01]
 [6.29001651e-09]
 [9.94098067e-01]
 [9.99951482e-01]
 [6.36178527e-07]
 [9.99915242e-01]
 [9.99857306e-01]
 [2.06748268e-07]
 [9.99386668e-01]
 [9.99342084e-01]
 [2.70023174e-05]
 [6.58274803e-05]
 [9.99551713e-01]
 [6.21894136e-09]
 [9.99993920e-01]
 [9.92742717e-01]
 [7.84848159e-11]
 [2.49450750e-06]
 [7.90688119e-08]
 [9.99939024e-01]
 [9.99990165e-01]
 [5.70074326e-06]
 [2.93477487e-09]
 [5.62023313e-04]
 [9.30062640e-07]
 [9.99996

In [9]:
# 轉換預測結果為二元標籤
predictions = (predictions > 0.5).astype(int)
predictions

array([[0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
    

In [10]:
# 保存模型
model.save('binary_classification_model.h5')

/Users/hongyicheng/.pyenv/versions/3.8.10/lib/python3.8/site-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [11]:
# 讀取模型
loaded_model = tf.keras.models.load_model('binary_classification_model.h5')

In [16]:
# 驗證讀取的模型
# loaded_model.evaluate(X_test, y_test)
from sklearn.metrics import accuracy_score
accuracy_score((loaded_model.predict(X_test) > 0.5).astype(int), y_test)

10/10 [==============================] - 0s 554us/step


0.96

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.datasets import load_iris
import tensorflow as tf

# 載入 Iris 數據集
iris = load_iris()
X = iris.data
y = iris.target

# One-hot 編碼標籤
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y.reshape(-1, 1))

# 分割數據為訓練集和測試集
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# 標準化數據
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 建立多元分類神經網路
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_dim=X_train.shape[1]),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')  # 輸出層，使用 softmax 激活函數進行多元分類
])

# 設定優化器
optimizer = tf.keras.optimizers.Adam()
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

# 訓練模型
model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.2)

# 評估模型
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}, Test Accuracy: {accuracy}')

# 進行預測
predictions = model.predict(X_test)
predicted_classes = tf.argmax(predictions, axis=1).numpy()
true_classes = tf.argmax(y_test, axis=1).numpy()

from sklearn.metrics import accuracy_score
accuracy_score(predicted_classes, true_classes)

/Users/hongyicheng/.pyenv/versions/3.8.10/lib/python3.8/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


Epoch 1/50
3/3 [==============================] - 0s 50ms/step - loss: 1.0045 - accuracy: 0.6310 - val_loss: 0.9805 - val_accuracy: 0.5714
Epoch 2/50
3/3 [==============================] - 0s 10ms/step - loss: 0.9036 - accuracy: 0.7143 - val_loss: 0.9121 - val_accuracy: 0.5714
Epoch 3/50
3/3 [==============================] - 0s 9ms/step - loss: 0.8145 - accuracy: 0.7262 - val_loss: 0.8531 - val_accuracy: 0.5714
Epoch 4/50
3/3 [==============================] - 0s 9ms/step - loss: 0.7390 - accuracy: 0.7262 - val_loss: 0.8021 - val_accuracy: 0.5714
Epoch 5/50
3/3 [==============================] - 0s 9ms/step - loss: 0.6687 - accuracy: 0.7262 - val_loss: 0.7560 - val_accuracy: 0.5714
Epoch 6/50
3/3 [==============================] - 0s 8ms/step - loss: 0.6099 - accuracy: 0.7262 - val_loss: 0.7156 - val_accuracy: 0.5714
Epoch 7/50
3/3 [==============================] - 0s 9ms/step - loss: 0.5547 - accuracy: 0.7381 - val_loss: 0.6806 - val_accuracy: 0.5714
Epoch 8/50
3/3 [================

0.9555555555555556

- [argmax, softmax](https://www.youtube.com/watch?v=KpKog-L9veg)

In [6]:
import numpy as np
np.argmax(predictions, axis=1), predictions

(array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 2, 1, 0, 0, 2, 1,
        0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
        0]),
 array([[2.93027611e-08, 2.57853153e-05, 9.99974132e-01],
        [3.69217712e-04, 9.98919249e-01, 7.11455708e-04],
        [9.99832988e-01, 1.65003425e-04, 1.99673946e-06],
        [5.93415024e-08, 4.53171437e-04, 9.99546707e-01],
        [9.99526739e-01, 4.67904145e-04, 5.33094817e-06],
        [1.42501602e-08, 1.31870966e-05, 9.99986768e-01],
        [9.99557078e-01, 4.36936738e-04, 6.00881458e-06],
        [1.56319595e-03, 8.78198266e-01, 1.20238513e-01],
        [7.08127220e-04, 8.93778682e-01, 1.05513245e-01],
        [9.47590824e-03, 9.72773492e-01, 1.77506376e-02],
        [1.08126624e-04, 8.34408328e-02, 9.16451037e-01],
        [5.10396110e-03, 9.35107589e-01, 5.97885251e-02],
        [6.56511681e-03, 9.67217743e-01, 2.62170639e-02],
        [1.32170983e-03, 5.79447031e-01, 4.19231325e-01],
        [4.86674206e-03, 7.

In [7]:
true_classes

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0,
       0])

In [18]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.datasets import load_iris
import tensorflow as tf

# 載入 Iris 數據集
iris = load_iris()
X = iris.data
y = iris.target

# One-hot 編碼標籤
encoder = OneHotEncoder(sparse=False)
# new1_y = encoder.fit_transform(y.reshape(-1, 1))
# new2_y = encoder.fit_transform(y)
# y.reshape(-1, 1), y
import pandas as pd
y = df[["label"]]

0
0    0
1    0
2    0
3    0
4    0
..  ..
145  2
146  2
147  2
148  2
149  2

[150 rows x 1 columns]

In [ ]:
classifaction_report()